"""add public gallery

Revision ID: 18a6c7730164
Revises: 53c34705ff56
Create Date: 2026-08-20 20:17:21.197938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a6c7730164'
down_revision: Union[str, Sequence[str], None] = '53c34705ff56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('review_comment', sa.String(length=255), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_public_images_id'), 'public_images', ['id'], unique=False)
    op.create_index(op.f('ix_public_images_image_id'), 'public_images', ['image_id'], unique=False)
    op.create_index(op.f('ix_public_images_status'), 'public_images', ['status'], unique=False)
    op.create_index(op.f('ix_public_images_user_id'), 'public_images', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False, comment='角色：user/admin'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_public_images_user_id'), table_name='public_images')
    op.drop_index(op.f('ix_public_images_status'), table_name='public_images')
    op.drop_index(op.f('ix_public_images_image_id'), table_name='public_images')
    op.drop_index(op.f('ix_public_images_id'), table_name='public_images')
    op.drop_table('public_images')
    # ### end Alembic commands ###
