"""add is_visible to public_images

Revision ID: 381df8ee6844
Revises: 18a6c7730164
Create Date: 2026-08-21 02:43:30.629304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '381df8ee6844'
down_revision: Union[str, Sequence[str], None] = '18a6c7730164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('public_images', sa.Column('is_visible', sa.Boolean(), server_default='1', nullable=False, comment='普通用户是否可见'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('public_images', 'is_visible')
    # ### end Alembic commands ###
