"""add user custom name composite index

Revision ID: 3d403e9cd8de
Revises: 5d36dbeec9e5
Create Date: 2026-08-27 19:06:23.858364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d403e9cd8de'
down_revision: Union[str, Sequence[str], None] = '5d36dbeec9e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_images_user_custom_name', 'images', ['user_id', 'custom_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_images_user_custom_name', table_name='images')
    # ### end Alembic commands ###
