"""add comments to users uid avatar

Revision ID: 5d36dbeec9e5
Revises: 3ef0848fd7ac
Create Date: 2026-08-27 16:52:49.589681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d36dbeec9e5'
down_revision: Union[str, Sequence[str], None] = '3ef0848fd7ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'uid',
               existing_type=mysql.VARCHAR(length=36),
               comment='对外唯一标识（UUID，不可修改）',
               existing_nullable=False)
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.VARCHAR(length=512),
               comment='头像 URL',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='头像 URL',
               existing_nullable=True)
    op.alter_column('users', 'uid',
               existing_type=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='对外唯一标识（UUID，不可修改）',
               existing_nullable=False)
    # ### end Alembic commands ###
