"""add ai_tasks table

Revision ID: 75c68df27de1
Revises: 3d403e9cd8de
Create Date: 2026-09-10 19:05:51.300869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c68df27de1'
down_revision: Union[str, Sequence[str], None] = '3d403e9cd8de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=32), nullable=False, comment='任务类型'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='pending/processing/completed/failed/cancelled'),
    sa.Column('progress', sa.Integer(), nullable=False, comment='阶段式进度 0-100'),
    sa.Column('message', sa.String(length=255), nullable=True, comment='阶段文案'),
    sa.Column('payload', sa.Text(), nullable=True, comment='任务参数 JSON（输入图路径/指令/标记色）'),
    sa.Column('result_path', sa.String(length=500), nullable=True, comment='结果图文件路径'),
    sa.Column('error', sa.String(length=500), nullable=True, comment='失败原因'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_id'), 'ai_tasks', ['id'], unique=False)
    op.create_index('ix_ai_tasks_status', 'ai_tasks', ['status'], unique=False)
    op.create_index('ix_ai_tasks_user_created', 'ai_tasks', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_tasks_user_id'), 'ai_tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tasks_user_id'), table_name='ai_tasks')
    op.drop_index('ix_ai_tasks_user_created', table_name='ai_tasks')
    op.drop_index('ix_ai_tasks_status', table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_id'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    # ### end Alembic commands ###
