"""split public gallery tags from image tags

Revision ID: 87184799610b
Revises: 75c68df27de1
Create Date: 2026-09-14 16:39:46.546398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87184799610b'
down_revision: Union[str, Sequence[str], None] = '75c68df27de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    阶段 19：把「公共图库标签」从 Image 上拆出来，改用独立的 public_image_tags。
    建表后必须把存量数据复制过去，否则历史公共图库的标签会全部消失。

    用「复制」而非「移动」：image_tags 要保留下来作为个人图库标签。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('public_image_tags',
    sa.Column('public_image_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['public_image_id'], ['public_images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('public_image_id', 'tag_id')
    )
    # ### end Alembic commands ###
    # 存量搬运：每条公共图库记录，把它对应图片现有的标签复制一份作为公开标签
    op.execute(
        sa.text(
            "INSERT INTO public_image_tags (public_image_id, tag_id) "
            "SELECT pi.id, it.tag_id "
            "FROM public_images pi "
            "JOIN image_tags it ON it.image_id = pi.image_id"
        )
    )


def downgrade() -> None:
    """Downgrade schema.

    回退时先把公开标签并回 image_tags（旧行为是公共图库读 image.tags），
    再删表，避免回退丢失升级期间新增的公开标签。INSERT IGNORE 跳过已存在的关联。
    """
    op.execute(
        sa.text(
            "INSERT IGNORE INTO image_tags (image_id, tag_id) "
            "SELECT pi.image_id, pit.tag_id "
            "FROM public_image_tags pit "
            "JOIN public_images pi ON pi.id = pit.public_image_id"
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('public_image_tags')
    # ### end Alembic commands ###
